sudo: required

branches:
  only:
    - master

services:
  - docker

before_install:
  # install heroku CLI
  - curl https://cli-assets.heroku.com/install.sh | sh

script:
  - sudo docker-compose build --build-arg ASPNETCORE_CONNECTION=$ASPNETCORE_CONNECTION
  - sudo docker login --username $HEROKU_EMAIL --password $HEROKU_AUTH_TOKEN registry.heroku.com
  - sudo docker tag web registry.heroku.com/$HEROKU_APP_NAME/web
  - sudo docker push registry.heroku.com/$HEROKU_APP_NAME/web