language: csharp
sudo: required
dotnet: 2.2

branches:
  only:
    - master

env:
  global:
    - ASPNETCORE_CONNECTION=$ASPNETCORE_CONNECTION

services:
  - docker

before_install:
  # install heroku CLI
  - curl https://cli-assets.heroku.com/install.sh | sh

script:
  - sudo docker-compose build
  - sudo docker login --username $HEROKU_EMAIL --password $HEROKU_AUTH_TOKEN registry.heroku.com
  - sudo docker tag web registry.heroku.com/$HEROKU_APP_NAME/web
  - sudo docker push registry.heroku.com/$HEROKU_APP_NAME/web
  - sudo heroku container:release web -a $HEROKU_APP_NAME